modLoader = "javafml"
loaderVersion = "[${min_forge_loader},)"
#issueTrackerURL = ""
license = "Insert License Here"

[[mods]]
modId = "${modid}"
version = "${version}"
displayName = "Building Wands"
authors = "Me!"
description = '''
Building Wands!
'''
#logoFile = ""

[[dependencies.wands]]
modId = "forge"
mandatory = true
versionRange = "[${min_forge_loader},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.wands]]
modId = "minecraft"
mandatory = true
versionRange = "[${min_minecraft_version},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.wands]]
modId = "architectury"
mandatory = true
versionRange = "[${min_architectury},)"
ordering = "AFTER"
side = "BOTH"