modLoader = "javafml"
loaderVersion = "[36,)"
#issueTrackerURL = ""
license = "Insert License Here"

[[mods]]
modId = "wands"
version = "${version}"
displayName = "Building Wands"
authors = "nicguzzo"
description = '''
Building Wands!
'''
#logoFile = ""

[[dependencies.wands]]
modId = "forge"
mandatory = true
versionRange = "[36,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.wands]]
modId = "minecraft"
mandatory = true
versionRange = "[1.16.5,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.wands]]
modId = "architectury"
mandatory = true
versionRange = "[1.32.63,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.wands]]
modId = "cloth-config"
mandatory = true
versionRange = "[4.14.64,)"

